### ISSUE TITLE
Manifest.json dosen't work

### ISSUE THREAD

**Issue by balintAlexandru** [dcode-youtube/getting-started-pwa#1]
Hi, i watch your youtube tutorial do the same think, add manifest.json link and when i want to test the code the console show me this error : 
Access to manifest at 'file:///C:/Users/Unknown/Desktop/PWA/manifest.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
GET file:///C:/Users/Unknown/Desktop/PWA/manifest.json net::ERR_FAILED
Can you help me with this error, thanks !

**Comment by dcode-youtube** [comment]
@balintAlexandru I've just done a video on this:
https://youtu.be/nx8E5BF0XuE

In short, you need to use a web server like the Live Server VS Code extension or XAMPP to host your files.
